version: '3'

volumes:
  app_database: {}
  app_memcached: {}

services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    depends_on:
      - php
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/symfony-3.conf:/etc/nginx/conf.d/default.conf
      - ./docker/logs/nginx/:/var/log/nginx
  php:
    build: ./docker/php
    hostname: app_hostname
    volumes:
      - ./:/var/www/app
      - ./docker/data/composer:/home/utente/.composer
    environment:
      - APP_ENV=${APP_ENV}
  servicedb:
    image: mysql:5.7
    restart: always
    volumes:
      - app_database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app_db
    command: mysqld --sql_mode=""
    ports:
      - 3307:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    depends_on:
      - servicedb
    environment:
      - PMA_HOST=servicedb
  servicememcached:
    image: memcached:latest
    volumes:
      - app_memcached:/var/lib/memcached
