dddapp_v1_signup_utente:
  path: /signup
  defaults: { _controller: UtenteDDDExample\Infrastructure\Delivery\Http\Controller\Utente\UtentePubblicoController::postSignupUtente }
  methods: [POST]
  requirements:
    _format: json

dddapp_v1_login_utente:
  path: /login
  defaults: { _controller: UtenteDDDExample\Infrastructure\Delivery\Http\Controller\Utente\AuthController::postLoginUtente }
  methods: [POST]
  requirements:
    _format: json

dddapp_v1_show_utente:
  path: /utente/{utenteId}
  defaults: { _controller: UtenteDDDExample\Infrastructure\Delivery\Http\Controller\Utente\UtentePrivatoController::getShowUtente }
  methods: [GET]
  requirements:
    _format: json

dddapp_v1_enable_utente:
  path: /utente/{utenteId}/enable
  defaults: { _controller: UtenteDDDExample\Infrastructure\Delivery\Http\Controller\Utente\UtentePrivatoController::patchEnableUtente }
  methods: [PATCH]
  requirements:
    _format: json
