services:

  dddapp.create_utente.command:
    class: UtenteDDDExample\Infrastructure\Delivery\Console\Utente\CreateUtenteCommand
    tags:
    - { name: 'console.command' }
    arguments:
    - '@dddapp.transactional.register_utente.service'
